GROQ_API_KEY: "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"
AI_MODEL: "mixtral-8x7b"
UPLOAD_FOLDER: "uploads"
ALLOWED_EXTENSIONS: ["arxml"]
ENABLE_RAG_VALIDATION: true
ENABLE_SCHEMA_CHECK: true
ENABLE_CONSISTENCY_CHECKS: true
DEPLOYMENT_ENV: "local"
log_file: "logs/app.log"
